### ISSUE TITLE
When I use the extension I get an error

### ISSUE THREAD

**Issue by Websteria** [nerdyrodent/StableBot#1]
Loading the extension "sd_api_bot"... Ok.
/home/jeff/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Traceback (most recent call last):
  File "/home/jeff/text-generation-webui/server.py", line 532, in <module>
    create_interface()
  File "/home/jeff/text-generation-webui/server.py", line 514, in create_interface
    extensions_module.create_extensions_block()
  File "/home/jeff/text-generation-webui/modules/extensions.py", line 69, in create_extensions_block
    extension.ui()
  File "/home/jeff/text-generation-webui/extensions/sd_api_bot/script.py", line 193, in ui
    generate_now_btn.click(chat.cai_chatbot_wrapper, shared.input_params, shared.gradio['display'], show_progress=shared.args.no_stream)
KeyError: 'display'

This happens everytime. I put the sd_api_bot in the extensions folder and it looks like all the others.

**Comment by nevaluoto** [comment]
I was having the same error, but launching with `python server.py --chat` lets you enable the `sd_api_bot` in the Interface mode settings and it'll work fine.

**Comment by nerdyrodent** [comment]
Yes, this is for chat mode.
