### ISSUE TITLE
StableBot no longer works a lot of errors.

### ISSUE THREAD

**Issue by CRCODE22** [nerdyrodent/StableBot#5]
Traceback (most recent call last):
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "D:\oobabooga_windows\text-generation-webui\modules\chat.py", line 256, in regenerate_wrapper
    for history in chatbot_wrapper('', state, regenerate=True):
  File "D:\oobabooga_windows\text-generation-webui\modules\chat.py", line 188, in chatbot_wrapper
    visible_reply = apply_extensions("output", visible_reply)
  File "D:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 112, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "D:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 58, in _apply_string_extensions
    text = getattr(extension, function_name)(text)
  File "D:\oobabooga_windows\text-generation-webui\extensions\sd_api_bot\script.py", line 136, in output_modifier
    image = get_SD_pictures(string)
  File "D:\oobabooga_windows\text-generation-webui\extensions\sd_api_bot\script.py", line 90, in get_SD_pictures
    for img_str in r['images']:
KeyError: 'images'

**Comment by nerdyrodent** [comment]
My suggestion would be to reverse the changes you made in order to go back to when it did work for you. I guess it could be another extension or something?

**Comment by CRCODE22** [comment]
> My suggestion would be to reverse the changes you made in order to go back to when it did work for you. I guess it could be another extension or something?

Thank you it seems this was the problem: You need to add --api to webui.py

run_cmd("python server.py --chat --model-menu --threads 8 --wbits 4 --groupsize 128 --model_type llama --api --listen-port 7861 --listen --extension sd_api_pictures send_pictures", environment=True)

This solved the problem
