### ISSUE TITLE
Aaand it's broken

### ISSUE THREAD

**Issue by kriimakt** [nerdyrodent/StableBot#6]
Doesn't seem to work anymore, when I try to activate the extension I get this message :

Traceback (most recent call last):
  File "D:\oobabooga_windows\text-generation-webui\server.py", line 997, in <module>
    create_interface()
  File "D:\oobabooga_windows\text-generation-webui\server.py", line 901, in create_interface
    extensions_module.create_extensions_block()
  File "D:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 153, in create_extensions_block
    extension.ui()
  File "D:\oobabooga_windows\text-generation-webui\extensions\sd_api_bot\script.py", line 193, in ui
    generate_now_btn.click(chat.cai_chatbot_wrapper, shared.input_params, shared.gradio['display'], show_progress=shared.args.no_stream)
AttributeError: module 'modules.chat' has no attribute 'cai_chatbot_wrapper'. Did you mean: 'chatbot_wrapper'?

**Comment by kriimakt** [comment]
Ok I fixed it by changing cai_chatbot_wrapper for chatbot_wrapper, and the extension loaded. But now I get this error when I talk to the bot :

Traceback (most recent call last):
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "D:\oobabooga_windows\text-generation-webui\modules\chat.py", line 307, in generate_chat_reply_wrapper
    for history in generate_chat_reply(text, state, regenerate, _continue):
  File "D:\oobabooga_windows\text-generation-webui\modules\chat.py", line 301, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue):
  File "D:\oobabooga_windows\text-generation-webui\modules\chat.py", line 230, in chatbot_wrapper
    visible_reply = apply_extensions("output", visible_reply)
  File "D:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 183, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "D:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 58, in _apply_string_extensions
    text = getattr(extension, function_name)(text)
  File "D:\oobabooga_windows\text-generation-webui\extensions\sd_api_bot\script.py", line 136, in output_modifier
    image = get_SD_pictures(string)
  File "D:\oobabooga_windows\text-generation-webui\extensions\sd_api_bot\script.py", line 90, in get_SD_pictures
    for img_str in r['images']:
KeyError: 'images'

**Comment by kriimakt** [comment]
Ok my bad, I started SD with --api and it works now !
