### ISSUE TITLE
Does not work with the latest version of text generation webui

### ISSUE THREAD

**Issue by CRCODE22** [nerdyrodent/StableBot#8]
Traceback (most recent call last):
  File "/root/text-generation-webui/server.py", line 1173, in <module>
    create_interface()
  File "/root/text-generation-webui/server.py", line 1067, in create_interface
    extensions_module.create_extensions_block()
  File "/root/text-generation-webui/modules/extensions.py", line 176, in create_extensions_block
    extension.ui()
  File "/root/text-generation-webui/extensions/sd_api_bot/script.py", line 193, in ui
    generate_now_btn.click(chat.cai_chatbot_wrapper, shared.input_params, shared.gradio['display'], show_progress=shared.args.no_stream)
AttributeError: module 'modules.chat' has no attribute 'cai_chatbot_wrapper'. Did you mean: 'chatbot_wrapper'?

**Comment by nerdyrodent** [comment]
The original extension can now be used in "Adventure Mode" to replicate how this worked
